### ISSUE TITLE
SQLTimestampCoercibleType coercion roundtrip fails; timezone related

### ISSUE THREAD

**Issue by ldcasillas-progreso** [Cascading/lingual#29]
I'm using Lingual 1.1.0.  This is the test case I've written, which I understand ought to succeed:

```
import static org.hamcrest.Matchers.*;
import static org.junit.Assert.assertThat;

@Test
public void sqlTimestampCoercibleTypeRoundtrip() {
    Timestamp ts = new Timestamp(System.currentTimeMillis());
    Fields fields = new Fields("ts", new SQLTimestampCoercibleType());
    Tuple tuple = Tuple.size(1);
    TupleEntry entry = new TupleEntry(fields, tuple);
    entry.setObject("ts", ts);

    assertThat("Timestamp value roundtrip", entry.getObject("ts", Timestamp.class), equalTo((Object)ts));
}
```

Result of running the test case:

```
java.lang.AssertionError: Timestamp value roundtrip
Expected: <2014-07-07 22:07:12.082>
     but: was <2014-07-08 05:07:12.082>
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at com.progressfin.sqltaps.SQLTapsTest.sqlTimestampCoercibleTypeRoundtrip(SQLTapsTest.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
```

It's 7 hours off.  I'm in California, which is UTC-7 right now.

**Comment by ldcasillas-progreso** [comment]
Maybe this unreleased commit fixes my issue?

https://github.com/Cascading/lingual/commit/c400bf5558e2fc136f89cfd68ae3e7684250d229

**Comment by ldcasillas-progreso** [comment]
Yes, it does!  I tried lingual-core:1.1.1-wip-31 and the test case passes.  Closing this issue.

**Comment by fs111** [comment]
I was about to ask you to try that version. Glad it is fixed. It is probably a good idea to sign up for the lingual-user group, where we announce such things. I hope we get to do the 1.1.1 release this week.
