### ISSUE TITLE
Support local catalog on Windows

### ISSUE THREAD

**Issue by joeposner** [Cascading/lingual#9]
This occurs:

 ERROR platform.PlatformBroker: error starting connection
java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\guoma\workspaceCascadingGuide\LingualMaven\src\main\resources\data\example
    at java.net.URI.create(URI.java:859)
    at cascading.lingual.platform.PlatformBroker.createSchemaNameFrom(PlatformBroker.java:628)
    at cascading.lingual.catalog.SchemaCatalogManager.createSchemaDefAndTableDefsFor(SchemaCatalogManager.java:238)
    at cascading.lingual.catalog.SchemaCatalogManager.createSchemaDefAndTableDefsFor(SchemaCatalogManager.java:223)
    at cascading.lingual.platform.PlatformBroker.loadTransientSchemas(PlatformBroker.java:672)
    at cascading.lingual.platform.PlatformBroker.loadCatalogManager(PlatformBroker.java:389)
    at cascading.lingual.platform.PlatformBroker.getCatalogManager(PlatformBroker.java:270)
    at cascading.lingual.platform.PlatformBroker.startConnection(PlatformBroker.java:174)
    at cascading.lingual.jdbc.LingualConnection.initialize(LingualConnection.java:128)
    at cascading.lingual.jdbc.LingualConnection.<init>(LingualConnection.java:80)
    at SC.<init>(Unknown Source)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at cascading.lingual.jdbc.JaninoFactory.create(JaninoFactory.java:148)
    at cascading.lingual.jdbc.JaninoFactory.createConnection(JaninoFactory.java:45)
    at cascading.lingual.jdbc.Driver.connect(Driver.java:172)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:233)
    at lingual.LingualMaven.JdbcExample.run(JdbcExample.java:17)
    at lingual.LingualMaven.JdbcExample.main(JdbcExample.java:11)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\guoma\workspaceCascadingGuide\LingualMaven\src\main\resources\data\example
    at java.net.URI$Parser.fail(URI.java:2829)
    at java.net.URI$Parser.checkChars(URI.java:3002)
    at java.net.URI$Parser.parse(URI.java:3039)
    at java.net.URI.<init>(URI.java:595)
    at java.net.URI.create(URI.java:857)

**Comment by joeposner** [comment]
Fixed in wip-1.0-301
